apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sfapm
spec:
  releaseName: sfapm
  chart:
    spec:
      chart: sfapm-python3
      sourceRef:
        kind: HelmRepository
        name: snappyflow
        namespace: flux-system
  interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: sfapm-helm-values