apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sfapm
spec:
  releaseName: sfapm
  chart:
    spec:
      chart: sfapm-python3
      sourceRef:
        kind: HelmRepository
        name: snappyflow
        namespace: flux-system
  interval: 5m
  values:
    imagePullSecrets:
      - name: snappyflowdockersecret
    postgresql:
      persistence:
        enabled: false
    redis:
      persistence:
        enabled: false
    enableDebug: true
    sfapmui:
      replicaCount: 1
      autoscaling:
        enabled: false
    sfapm:
      replicaCount: 1
      autoscaling:
        enabled: false
      resources:
        limits: 
          cpu: 2000m
          memory: 2000Mi
        requests:
          cpu: 100m
          memory: 256Mi
    sfapm_celery:
      periodic:
        replicaCount: 1
        autoscaling:
          enabled: false
    vizbuilder:
      replicaCount: 1
      autoscaling:
        enabled: false
    vizbuilder_celery:
      alert:
        replicaCount: 1
    commands:
      replicaCount: 1
      autoscaling:
        enabled: false
    sftrace:
      replicaCount: 1
      autoscaling:
        enabled: false