apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sfapm
spec:
  releaseName: sfapm
  chart:
    spec:
      chart: sfapm-python3
      sourceRef:
        kind: HelmRepository
        name: snappyflow
        namespace: flux-system
  interval: 5m
  valuesFrom:
    - kind: ConfigMap
      name: sfapm-helm-values
  postRenderers:
    - kustomize:
        patchesStrategicMerge:
          - kind: Deployment
            apiVersion: apps/v1
            metadata:
              name: sfapm-sfapm-python3-apm
            spec:
              template:
                spec:
                  containers:
                    - name: sfapm
                      args:
                        - gunicorn snappyflow.wsgi:application --workers=2 --threads=4 --timeout=120
                      readinessProbe:
                        initialDelaySeconds: 120
                      livenessProbe:
                        initialDelaySeconds: 120